[versions]
skija = "0.143.13"
skija_types = "0.2.0"

fabricLoom = "1.16.+"

[libraries]
skija_shared = { group = "io.github.humbleui", name = "skija-shared", version.ref = "skija" }
skija_types = { group = "io.github.humbleui", name = "types", version.ref = "skija_types" }
skija_windows = { group = "io.github.humbleui", name = "skija-windows-x64", version.ref = "skija" }
skija_linux_x64 = { group = "io.github.humbleui", name = "skija-linux-x64", version.ref = "skija" }
skija_linux_arm64 = { group = "io.github.humbleui", name = "skija-linux-arm64", version.ref = "skija" }
skija_macos_x64 = { group = "io.github.humbleui", name = "skija-macos-x64", version.ref = "skija" }
skija_macos_arm64 = { group = "io.github.humbleui", name = "skija-macos-arm64", version.ref = "skija" }

[plugins]
fabricLoom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabricLoom" }
legacyLooming = { id = "ploceus", version.ref = "fabricLoom" }